# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JH-WHKmW91zHLyrOl--Wj2MdCNg1QfGz
"""

import numpy as np
import matplotlib.pyplot as plt

# 초기화
k = 10000
M = 2000
m = 0
pp = np.zeros(M)

for N in range(k, k * M + 1, k):
    m += 1
    x = np.random.rand(N)
    y = np.random.rand(N)
    z = np.sqrt(x**2 + y**2)
    c = np.sum(z <= 1)  # inside of 1/4 circle
    d = N - c  # outside of 1/4 circle
    pp[m - 1] = c * 4 / N

# 그래프 그리기
plt.figure(1)
plt.clf()
plt.plot(np.arange(1, M + 1), pp)
plt.grid()
plt.plot([1, M], [np.pi, np.pi], 'r', linewidth=2)
plt.xlabel('Number of Random Points (*10^4)')
plt.ylabel('Estimation of π')

plt.figure(2)
plt.clf()
plt.plot(x, y, '.')
plt.grid()
xx = np.arange(0, 1.001, 0.001)
plt.plot(xx, np.sqrt(1 - xx**2), 'r', linewidth=2)

plt.show()